
# Disable automatic AppVeyor build logic
build: off
skip_branch_with_pr: true

image:
  - Visual Studio 2017
  - Visual Studio 2019
  - Ubuntu1804
  - macos

for:
-
  matrix:
    only:
      - image: Visual Studio 2017
  install:
    - choco install -y winpcap
    - choco install -y codecov
  build_script:
    - dotnet build -c Release
  test_script:
    - dotnet test --test-adapter-path:. --logger:Appveyor -p:CollectCoverage=true
    - codecov -f **\*.opencover.xml

-
  matrix:
    only:
      - image: Visual Studio 2019
  install:
    - choco install -y codecov
    # an OEM installer is required for newer versions of npcap
    - choco install -y npcap --version 0.86
  build_script:
    - dotnet build -c Release
  test_script:
    - dotnet test --test-adapter-path:. --logger:Appveyor -p:CollectCoverage=true --filter TestCategory!=RemotePcap
    - codecov -f **\*.opencover.xml

-
  matrix:
    only:
      - image: Ubuntu1804
  install:
    - sudo apt-get -qy install libpcap-dev
  test_script:
    - sudo -E dotnet test --test-adapter-path:. --logger:Appveyor -p:CollectCoverage=true --filter TestCategory!=SendPacket
    - bash <(curl -s https://codecov.io/bash)

-
  matrix:
    only:
      - image: macos
  install:
    - brew update
    - brew install libpcap
  test_script:
    - sudo -E dotnet test --test-adapter-path:. --logger:Appveyor -p:CollectCoverage=true
    - bash <(curl -s https://codecov.io/bash)
